* The NumberGuessingGame program

The program simulates a guessing game of which a user guesses a number from 1 to 10. The answer is randomly generated then a user enters a number via the console. 
** Each time a number is entered, one of the following three possible outputs will be displayed. 
 1. “Congratulations!”	if the number entered is the same as the answer.
 2. “Try a lower number!” 	if the number entered is higher than the answer.
 3. “Try a higher number!” 	if the number entered is smaller than the answer.  

** The game ends when the user guesses the answer correctly or the user guesses the number incorrectly 5 times. 


* The ConfigurableNumberGuessingGame program

The program simulates a guessing game of which a user guesses a number from <min> to <max>. The answer is randomly generated then a user enters a number via the console. 
** Each time a number is entered, one of the following three possible outputs will be displayed. 
 1. “Congratulations!”	if the number entered is the same as the answer.
 2. “Try a lower number!” 	if the number entered is higher than the answer.
 3. “Try a higher number!” 	if the number entered is smaller than the answer.  

** The game ends when the user guesses the answer correctly or the user guesses the number incorrectly <numOfTries> times. 

** The program asks the user to enter the min value, the max value, and the maximum number of tries.
*** The program also checks and detects configuration settings that the user may enter as following
**** The program checks whether the max value is at least equal to the min value. If not, the program will keep asking for the new max value until the max value is not less than the max value. 
**** The program checks whether the number of maximum tries is greater than 0. If not, the program will keep asking for the new maximum tries until the maximum tries is greater than 0. 
**** The program checks whether a number is outside the minimum or maximum values. If it is, the program asks the user to enter a number again and does not increment the number of tries.  


* The NumberGuessingGames program

The program allows the user to play the [[ConfigurableNumberGuessingGame]] several times until the user indicates that he/she wants to stop playing the game.  
** The answer will be random each time the user chooses to play again. 
** On the other hand, the program will not ask the user to config (min,max,number of tries) again.
** After the game ends, the program gives an option to play again if the user enters “y” or “Y”. If the user enters other values, the program will quit and print the message  “Thank you for playing our games. Bye!"

